### ISSUE TITLE
Add border-radius to bottom left and bottom right corners of page

### ISSUE THREAD

**Issue by liam4** [OpenSprites/OpenSprites#10]
If we stick to using the current style (which I think we will, it looks good for a Scratch themed site) we should make the bottom couple borders round, eg:

```css
#main-page {
  border-radius-bottom-left: 3px;
}

#upload {
  border-radius-bottom-right: 3px;
}
```

or something along those lines.
