### ISSUE TITLE
Error message images not displaying

### ISSUE THREAD

**Issue by The-Cheese-Eater** [OpenSprites/OpenSprites#193]
For example, opensprites.org/lalalalala

**Comment by GrannyCookies** [comment]
It's because of the **REALLY STUPID** css rule:
```CSS
html body img {
	display: none;
}
```
I have no idea why it was ever put it place in the first place.
